---
title: "Assessing Non-native Species’ Impacts on Nature’s Contributions to People:
  A Meta-Analysis (Code). Full model Overall effect"
output:
  html_document:
    df_print: paged
---

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(metafor) # main package for meta-analysis in R
knitr::opts_knit$set(root.dir = 'C:/Users/ACER/Desktop/UniPotsdam/Spec+Master/R')
```

```{r, warning=FALSE, message=FALSE}
setwd('C:/Users/ACER/Desktop/UniPotsdam/Spec+Master/R')
data_no_dep_prop <- read.csv('data_cont.csv', header=TRUE, sep=',', dec='.' )
data_prop <- read.csv('data_prop.csv', header=TRUE, sep=',', dec='.' )
data <- read.csv('data_ready.csv', header = T, sep=',', dec='.')
m_overall <- rma.mv(
  yi_dir,
  vi,
  random = ~ 1 | ID,
  data = data,
  method = "REML"
)

funnel(m_overall)
```

# Full-category model per NCP

Average effect of invasion on the NCP, across all relevant proxies -> Random-effects model with random intercept for study_id (to handle non-independence)
For continuous and count data:
```{r, warning=FALSE, message=FALSE}

data_no_dep_prop$ncp_1[data_no_dep_prop$ncp_1 == "Regulating - Soil Quality"] <- "Soil fertility regulation"
data_no_dep_prop$ncp_1[data_no_dep_prop$ncp_1 == "Regulating - Freshwater quality"] <- "Water purification"
data_no_dep_prop$ncp_1[data_no_dep_prop$ncp_1 == "Regulating - Climate Change"] <- "Carbon storage and sequestration"
data_no_dep_prop$ncp_1[data_no_dep_prop$ncp_1 == "Regulating - Pollination"] <- "Pollination"
data_no_dep_prop$ncp_1[data_no_dep_prop$ncp_1 == "Regulating - Fire risk"] <- "Fire regulation"

m_overall <- rma.mv(
  yi_dir,
  vi,
  random = ~ 1 | ID,
  data = data_no_dep_prop,
  method = "REML"
)

overall_df <- data.frame(
  group = "Overall",
  estimate = as.numeric(m_overall$b),
  ci_lb = m_overall$ci.lb,
  ci_ub = m_overall$ci.ub
)
write.csv(overall_df,
          "overall_model_results.csv",
          row.names = FALSE)

```

```{r, warning=FALSE, message=FALSE}
results_full <- list()
ncps <- unique(data_no_dep_prop$ncp_1)
for (n in ncps) {
  
  dat_ncp <- data_no_dep_prop[data_no_dep_prop$ncp_1 == n, ]
  
  # Minimum size check
  if (nrow(dat_ncp) < 5) next
  
  m_full <- rma.mv( # check for rma documentation
    yi_dir,
    vi,
    random = ~ 1 | ID,
    data = dat_ncp,
    method = "REML"
  )
  
  results_full[[n]] <- m_full
}

sapply(results_full, function(x) x$b)

full_summary <- data.frame(
  ncp = names(results_full),
  estimate = sapply(results_full, function(x) x$b),
  ci_lb = sapply(results_full, function(x) x$ci.lb),
  ci_ub = sapply(results_full, function(x) x$ci.ub),
  pval = sapply(results_full, function(x) x$pval),
  tau2 = sapply(results_full, function(x) x$tau2)
)
full_summary
write.csv(full_summary,
          file = "full_model_results.csv",
          row.names = FALSE)

#visualisation
ncp_forest_cont <- data.frame(
  ncp = names(results_full),
  estimate = sapply(results_full, function(m) as.numeric(m$b)),
  ci_lb = sapply(results_full, function(m) m$ci.lb),
  ci_ub = sapply(results_full, function(m) m$ci.ub),
  k = sapply(results_full, function(m) m$k),
  stringsAsFactors = FALSE
)

par(mar = c(7,3,4,2))
par(xpd = NA) 
forest(
  x = ncp_forest_cont$estimate,
  ci.lb = ncp_forest_cont$ci_lb,
  ci.ub = ncp_forest_cont$ci_ub,
  slab = paste0(ncp_forest_cont$ncp, " (k = ", ncp_forest_cont$k, ")"),
  xlab = "Standardised effect size (Hedges' g )",
  refline = 0,
  cex = 0.9
  )

arrow_length <- 2
usr <- par("usr") 
mid <- 0  # change if neede 

y_arrow <- usr[3] + 0.2   # slightly below plot
y_text  <- usr[3] + 0.5   # text further below

arrows(mid, y_arrow, mid - arrow_length, y_arrow, col="red", lwd=2, length=0.08) 
arrows(mid, y_arrow, mid + arrow_length, y_arrow, col="darkgreen", lwd=2, length=0.08) 

text((mid - arrow_length), y_text, "Decreased function", col="red") 
text((mid + arrow_length), y_text, "Increased function", col="darkgreen")

```

For proportional data:
```{r, warning=FALSE, message=FALSE}
data_prop$ncp_1[data_prop$ncp_1 == "Regulating - Soil Quality"] <- "Soil fertility regulation"
data_prop$ncp_1[data_prop$ncp_1 == "Regulating - Climate Change"] <- "Carbon storage and sequestration"
data_prop$ncp_1[data_prop$ncp_1 == "Regulating - Pollination"] <- "Pollination"
data_pol <- subset(data_prop, ncp_1 == "Pollination")
m_overall <- rma.mv(
  yi_dir,
  vi,
  random = ~ 1 | ID,
  data = data_pol,
  method = "REML"
)

overall_df <- data.frame(
  group = "Overall",
  estimate = as.numeric(m_overall$b),
  ci_lb = m_overall$ci.lb,
  ci_ub = m_overall$ci.ub, 
  p = m_overall$p
)
write.csv(overall_df,
          "overall_model_results_prop.csv",
          row.names = FALSE)

results_full <- list()
ncps <- unique(data_pol$ncp_1)
for (n in ncps) {
  
  dat_ncp <- data_pol[data_pol$ncp_1 == n, ]
  
  # Minimum size check
  if (nrow(dat_ncp) < 5) next
  
  m_full <- rma.mv( # check for rma documentation
    yi_dir,
    vi,
    random = ~ 1 | ID,
    data = dat_ncp,
    method = "REML"
  )
  
  results_full[[n]] <- m_full
}

sapply(results_full, function(x) x$b)

full_summary <- data.frame(
  ncp = names(results_full),
  estimate = sapply(results_full, function(x) x$b),
  ci_lb = sapply(results_full, function(x) x$ci.lb),
  ci_ub = sapply(results_full, function(x) x$ci.ub),
  pval = sapply(results_full, function(x) x$pval),
  tau2 = sapply(results_full, function(x) x$tau2)
)
full_summary

#visualisation
ncp_forest_cont <- data.frame(
  ncp = names(results_full),
  estimate = sapply(results_full, function(m) as.numeric(m$b)),
  ci_lb = sapply(results_full, function(m) m$ci.lb),
  ci_ub = sapply(results_full, function(m) m$ci.ub),
  k = sapply(results_full, function(m) m$k),
  stringsAsFactors = FALSE
)

par(mar = c(7,3,4,2))
par(xpd = NA) 
forest(
  x = ncp_forest_cont$estimate,
  ci.lb = ncp_forest_cont$ci_lb,
  ci.ub = ncp_forest_cont$ci_ub,
  slab = paste0(ncp_forest_cont$ncp, " (k = ", ncp_forest_cont$k, ")"),
  xlab = "Standardised effect size (Hedges' g )",
  refline = 0,
  cex = 0.9
)

arrow_length <- 0.5
usr <- par("usr") 
mid <- 0  # change if neede 

y_arrow <- usr[3] + 0.2   # slightly below plot
y_text  <- usr[3] + 0.5   # text further below

arrows(mid, y_arrow, mid - arrow_length, y_arrow, col="red", lwd=2, length=0.08) 
arrows(mid, y_arrow, mid + arrow_length, y_arrow, col="darkgreen", lwd=2, length=0.08) 

text((mid - arrow_length), y_text, "Decreased function", col="red") 
text((mid + arrow_length), y_text, "Increased function", col="darkgreen")
```

